# -*- coding: utf-8 -*-
"""AI_W4_25_02_23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dw9FxcuKwyh8Y_2zGrPtjEFMuuxoWGK9
"""

pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt
x = np.arange(50,80,1)
slow = fuzz.trimf(x,[50,50,70])
medium = fuzz.trimf(x,[55,60,75])
medium_fast = fuzz.trimf(x,[60,65,80])
full_speed = fuzz.trimf(x,[65,70,85])
plt.figure()
plt.plot(x,slow,'r',linewidth=1.5,label = 'slow')
plt.plot(x,medium,'b',linewidth=1.5,label = 'slow')
plt.plot(x,medium_fast,'r',linewidth=1.5,label = 'slow')
plt.plot(x,full_speed,'b',linewidth=1.5,label = 'slow')

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
food = ctrl.Antecedent(np.arange(0,11,1),'food')
service = ctrl.Antecedent(np.arange(0,11,1),'service')
tip = ctrl.Consequent(np.arange(10,31,1),'tip')
food['poor'] = fuzz.trimf(food.universe,[0,0,5])
food['average'] = fuzz.trimf(food.universe,[0,5,10])
food['good'] = fuzz.trimf(food.universe,[5,10,10])
service['poor'] = fuzz.trimf(service.universe,[0,0,5])
service['average'] = fuzz.trimf(service.universe,[0,5,10])
service['good'] = fuzz.trimf(service.universe,[5,10,10])
tip['poor'] = fuzz.trimf(tip.universe,[5,5,10])
tip['average'] = fuzz.trimf(tip.universe,[5,10,15])
tip['good'] = fuzz.trimf(tip.universe,[10,10,15])


rule1 = ctrl.Rule(food['poor']& service['poor'],tip['poor'])
rule2 = ctrl.Rule(food['poor']& service['average'],tip['poor'])
rule3 = ctrl.Rule(food['poor']& service['good'],tip['average'])
rule4 = ctrl.Rule(food['average']& service['poor'],tip['poor'])
rule5 = ctrl.Rule(food['average']& service['average'],tip['average'])
rule6 = ctrl.Rule(food['average']& service['good'],tip['good'])
rule7 = ctrl.Rule(food['good']& service['poor'],tip['average'])
rule8 = ctrl.Rule(food['good']& service['average'],tip['good'])
rule9 = ctrl.Rule(food['good']& service['good'],tip['good'])

# Data
tipping_ctrl = ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5,rule6,rule7,rule8,rule9])
tipping = ctrl.ControlSystemSimulation(tipping_ctrl)
tipping.input['food'] = 6.5
tipping.input['service'] = 9.8
tipping.compute()
print(tipping.output['tip'])
tip.view(sim = tipping)
food.view(sim = tipping)
service.view(sim = tipping)

